#ifndef LOGCATEGORIES_H
#define LOGCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logStend)
Q_DECLARE_LOGGING_CATEGORY(logTrc)
Q_DECLARE_LOGGING_CATEGORY(logBattery)

#endif // LOGCATEGORIES_H
